// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_sgMRA_H_GEN_
#define RCPP_sgMRA_H_GEN_

#include "sgMRA_RcppExports.h"

#endif // RCPP_sgMRA_H_GEN_
