# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate thresheld pairwise distance
#'
#' @param locs An N x 2 matrix of spatial locations
#' @param locs_grid An N_grid x 2 matrix of spatial grids
#' @param radius The thresholded radius
#' @param n_neighbors The expected number of neighbors based on the MRA grid
#' @return The thresheld pairwise distance
#'
#' @export
distance_near_with_ddist_cpp <- function(locs, locs_grid, radius, n_neighbors = 68L) {
    .Call('_sgMRA_distance_near_with_ddist_cpp', PACKAGE = 'sgMRA', locs, locs_grid, radius, n_neighbors)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_sgMRA_RcppExport_registerCCallable', PACKAGE = 'sgMRA')
})
